### ISSUE TITLE
Ut Video Codec plug-in for Adobe Premiere Pro/Media Encoder

### ISSUE THREAD

**Issue by PCUser2021** [umezawatakeshi/utvideo#48] opened 2024-09-15 20:10 UTC
Hello

Please develop a Ut Video Codec plug-in for Adobe Premiere Pro/Media Encoder.

Thanks

**Comment by umezawatakeshi** [comment] 2024-09-17 13:27
duplicate of https://github.com/umezawatakeshi/utvideo/issues/42

**Closed as completed by umezawatakeshi** 2024-09-17 13:27 UTC
Labels: resolution: duplicate
